### ISSUE TITLE
Named array keys

### ISSUE THREAD

**Issue by butchewing** [zrashwani/arachnid#20]
What is the rationale for using named `$nodeUrl` and `$nodeText` array keys?

```
$childLinks[$hash]['original_urls'][$nodeUrl] = $nodeUrl;
$childLinks[$hash]['links_text'][$nodeText] = $nodeText;
```
[Crawler.php Line 363 & 364 ](https://github.com/zrashwani/arachnid/blob/master/src/Arachnid/Crawler.php#L363)

Would it not be more consistent and easier to parse if we changed to numerical keys?

```
$childLinks[$hash]['original_urls'][] = $nodeUrl;
$childLinks[$hash]['links_text'][] = $nodeText;
```

**Comment by zrashwani** [comment]
I made `$nodeUrl` and `$nodeText` array keys to avoid duplication in the array and force unique values - in case the same url's exists in many pages with the same link text.
do you have better idea how to implement?

**Comment by butchewing** [comment]
Ah, I see. Good point. I was simply trying to figure out a way to parse through the array without knowing the key name.
