### ISSUE TITLE
Adding a release

### ISSUE THREAD

**Issue by thewinterwind** [zrashwani/arachnid#23]
Hi, can you please add a release for commit 244180c3c74468c9dfd5aa19a8154b5ec5912f23?

We are not able to use HEAD anymore as we have Laravel 5.3 and your package now requires Illuminate/Support 5.4.

Thank you,
Anthony

**Comment by jackvial** [comment]
+1

**Comment by mightylal** [comment]
+1

**Comment by zrashwani** [comment]
The release now created https://github.com/zrashwani/arachnid/releases/tag/1.2

**Comment by thewinterwind** [comment]
@zrashwani sorry, I think there's a misunderstanding, we wanted a release for the commit before that: https://github.com/zrashwani/arachnid/commit/b4607e95606856b40a847ec058660561babd6f25
The latest one means your package cannot be installed on Laravel 5.3

**Comment by zrashwani** [comment]
@thewinterwind sorry, I misunderstood,
Here is the new release https://github.com/zrashwani/arachnid/releases/tag/1.2.0
this is the requested one, right?

**Comment by thewinterwind** [comment]
thanks, we are good now!

**Comment by thewinterwind** [comment]
great work on this package!
