### ISSUE TITLE
Undefined index: external_link

### ISSUE THREAD

**Issue by davidpaulalbert** [zrashwani/arachnid#27]
I'm getting an Undefined index: external_link error in LinksCollection.php (line 51). I'm suspecting it may be because the site I'm indexing has some "javascript:void(0)" links on buttons and so forth that are tied to jQuery events, etc. Wondering if you might have any insight or ideas. Any help would be greatly appreciated. Thanks.

**Comment by zrashwani** [comment]
Hello @davidpaulalbert 
can you give me the base url that you are trying to crawl?

**Comment by davidpaulalbert** [comment]
http://medianthealthcare.com

**Comment by zrashwani** [comment]
hello @davidpaulalbert 
I have tried to reproduce using the same link, but it is working normally,
here is simple statistics about crawling:
"--- links by depth ---"
"level#1"    60 
"level#2"    145
"level#3"    210
"level#4"    86

can you please re-try from your side?

**Comment by davidpaulalbert** [comment]
Thanks. I think it may have been a network issue with the site. I appreciate you looking into it as a potential bug--seems not to be.
