### ISSUE TITLE
Sites like linkedin should be probably excluded

### ISSUE THREAD

**Issue by neorganic** [zrashwani/arachnid#28]
Some social giants should be excluded from the results if they require login to be accessed - in order to only see the really broken links. With the current situation we get some false positives, with sites like linkedin.

**Comment by zrashwani** [comment]
Hello @neorganic 
sorry for late reply;
I think the best approach is to prevent scrapper from traversing linkedin links using `filterLinks` method similar as below:
```php

$links = $client->filterLinks(function ($link) {
                             //ignore scrapping link if linkedin
                              return strpos($link,"www.linkedin.com")===false; 
                        })
                        ->traverse()
                        ->getLinks();
```

**Comment by zrashwani** [comment]
closing for now, let me know if you still face issue
