### ISSUE TITLE
Does not support js-rendered sites

### ISSUE THREAD

**Issue by neorganic** [zrashwani/arachnid#30]
Sites like https://taxibambino.com or other sites that html is being rendered from js is not supported by this crawler and I understand that by design(being a back-end based crawler) this is not fixable. I am afraid that with the lacking support of js-only sites this crawler becomes obsolete.

**Comment by zrashwani** [comment]
Thank you @neorganic I will look for this issue in the weekend

**Comment by zrashwani** [comment]
closing for now, since Js-rendered site support is added in release 2.0, feel free to open new issue if there is any other issue
